---

- name: Update 'JVM_ARGS' variable within wlst script
  lineinfile:
    dest: "{{ oracle_home_dir }}/oracle_common/common/bin/wlst.sh"
    regexp: ^JVM_ARGS=
    line: JVM_ARGS="-Dprod.props.file='${WL_HOME}'/.product.properties ${WLST_PROPERTIES} ${JVM_D64} ${UTILS_MEM_ARGS} ${COMMON_JVM_ARGS} ${CONFIG_JVM_ARGS} -Djava.security.egd=file:///dev/urandom"
  when: weblogic_version == '12c'


# - lineinfile:
#     dest: "{{ oracle_soa_wls_home }}/common/bin/wlst.sh"
#     regexp: ^JVM_ARGS=
#     line: JVM_ARGS="-Dprod.props.file='${WL_HOME}'/.product.properties ${WLST_PROPERTIES} ${JVM_D64} ${MEM_ARGS} ${CONFIG_JVM_ARGS} -Djava.security.egd=file:///dev/urandom"
#   when: weblogic_version == '11g'
