---

- include: validate.yml

- include: prepare.yml
  become: yes
  when: weblogic_force_installation or (not weblogic_already_installed)

- include: install.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: weblogic_force_installation or (not weblogic_already_installed)

- include: create-domain.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: not weblogic_already_installed

- include: create-managed-server.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: not weblogic_already_installed
