#!/bin/bash

#
# This file is generated by Ansible
#

if [ $USER = "{{ oracle.user }}" ]; then
  if [ $SHELL = "/bin/ksh" ]; then
    ulimit -p {{ sys_ulimits.nproc[1]['value'] }}
    ulimit -n {{ sys_ulimits.nofile[1]['value'] }}
  else
    ulimit -u {{ sys_ulimits.nproc[1]['value'] }} -n {{ sys_ulimits.nofile[1]['value'] }}
  fi
fi
